# Generated by Django 5.2.3 on 2025-07-06 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_block_user', 'Can block user')], 'verbose_name': 'Пользователь',
                     'verbose_name_plural': 'Пользователи'},
        ),
    ]
