# Generated by Django 5.2.3 on 2025-06-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_emailmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingrecipient',
            name='personal_details',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sending', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время первой отправки')),
                ('close_sending', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания отправки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('sent', 'Запущена'), ('closed', 'Завершена')], max_length=9, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailings.emailmessage', verbose_name='сообщение')),
                ('recipient', models.ManyToManyField(related_name='recipients', to='mailings.mailingrecipient', verbose_name='получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['created_at'],
            },
        ),
    ]
