# Generated by Django 5.2.3 on 2025-06-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailingrecipient_personal_details_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='recipient',
            field=models.ManyToManyField(related_name='recipients', to='mailings.mailingrecipient', verbose_name='получатель'),
        ),
    ]
