# Generated by Django 5.2.3 on 2025-06-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_mailing_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
