# Generated by Django 5.2.3 on 2025-07-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mailings', '0005_emailmessage_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(
                choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], max_length=9,
                verbose_name='Статус'),
        ),
    ]
