# Generated by Django 5.2.3 on 2025-07-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mailings', '0007_mailingattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='owner_messages', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='owner_mailings', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='mailingrecipient',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='owner_recipients', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Владелец'),
        ),
    ]
