# Generated by Django 5.2.3 on 2025-07-06 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mailings', '0009_alter_mailing_options_alter_mailingrecipient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingrecipient',
            options={'ordering': ['email'], 'verbose_name': 'Получатель рассылки',
                     'verbose_name_plural': 'Получатели рассылки'},
        ),
    ]
